apiVersion: kafka.strimzi.io/v1
kind: KafkaRebalance
metadata:
  name: cluster-rebalance-add-brokers
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  mode: add-brokers
  brokers: [3, 4, 5]
